app:
  environment: prod
  message: Auth Service is running on Docker Infrastructure

spring:
  datasource:
    url: jdbc:postgresql://marketplace-postgres:5432/marketplace_db
    username: esra
    password: esra1234
  jpa:
    show-sql: false

  data:
    redis:
      host: marketplace-redis

  kafka:
    bootstrap-servers: marketplace-kafka:29092

logging:
  level:
    org.hibernate.SQL: WARN
    io.lettuce: WARN
    org.springframework.security: INFO
    org.esrakonya.backend: INFO