version: '3.8'

services:
  # --- INFRASTRUCTURE LAYER ---
  marketplace-postgres:
    image: postgres:16-alpine
    container_name: marketplace-postgres
    environment:
      - POSTGRES_DB=marketplace_db
      - POSTGRES_USER=esra
      - POSTGRES_PASSWORD=esra1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - marketplace-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U esra -d marketplace_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  marketplace-redis:
    image: redis:7-alpine
    container_name: marketplace-redis
    ports:
      - "6379:6379"
    networks:
      - marketplace-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  marketplace-zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: marketplace-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - marketplace-net

  marketplace-kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: marketplace-kafka
    depends_on:
      - marketplace-zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: marketplace-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://marketplace-kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - marketplace-net

  marketplace-zipkin:
    image: openzipkin/zipkin:3
    container_name: marketplace-zipkin
    ports:
      - "9411:9411" # Zipkin Dashboard
    networks:
      - marketplace-net

  marketplace-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: marketplace-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Only for dev/portfolio purposes
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    networks:
      - marketplace-net

  marketplace-logstash:
    image: docker.elastic.co/logstash/logstash:8.11.1
    container_name: marketplace-logstash
    volumes:
      - ./docker-config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    ports:
      - "5044:5044"
    environment:
      - LS_JAVA_OPTS=-Xms256m -Xmx256m
      - XPACK_MONITORING_ELASTICSEARCH_HOSTS=http://marketplace-elasticsearch:9200
    depends_on:
      - marketplace-elasticsearch
    networks:
      - marketplace-net

  marketplace-kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: marketplace-kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://marketplace-elasticsearch:9200
      # Senior Move: Disable security on the Kibana side to match Elasticsearch
      - XPACK_SECURITY_ENABLED=false
    depends_on:
      - marketplace-elasticsearch
    networks:
      - marketplace-net


  # --- MICROSERVICES LAYER ---
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://marketplace-postgres:5432/marketplace_db
      - LOGSTASH_HOST=marketplace-logstash
    depends_on:
      marketplace-postgres:
        condition: service_healthy
    networks:
      - marketplace-net

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://marketplace-postgres:5432/marketplace_db
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=marketplace-kafka:29092
      - SPRING_DATA_REDIS_HOST=marketplace-redis
      - LOGSTASH_HOST=marketplace-logstash
    depends_on:
      marketplace-postgres:
        condition: service_healthy
      marketplace-kafka:
        condition: service_started
      marketplace-redis:
        condition: service_healthy
    networks:
      - marketplace-net

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://marketplace-postgres:5432/marketplace_db
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=marketplace-kafka:29092
      - LOGSTASH_HOST=marketplace-logstash
    depends_on:
      marketplace-postgres:
        condition: service_healthy
      marketplace-kafka:
        condition: service_started
    networks:
      - marketplace-net

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8084:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=marketplace-kafka:29092
      - LOGSTASH_HOST=marketplace-logstash
    depends_on:
      marketplace-kafka:
        condition: service_started
    networks:
      - marketplace-net

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - LOGSTASH_HOST=marketplace-logstash
    depends_on:
      - auth-service
      - product-service
      - inventory-service
    networks:
      - marketplace-net

# --- NETWORK & VOLUMES ---
networks:
  marketplace-net:
    driver: bridge

volumes:
  postgres_data: