services:
  postgres-db:
    image: postgres:16-alpine
    container_name: marketplace-postgres
    environment:
      - POSTGRES_DB=marketplace_db
      - POSTGRES_USER=esra
      - POSTGRES_PASSWORD=esra1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - marketplace-net

  # --- NEW REDIS SERVICE ---
  redis:
    image: redis:7-alpine
    container_name: marketplace-redis
    ports:
      - "6379:6379"
    networks:
      - marketplace-net
    healthcheck: # Senior Tip: Ensure Redis is ready before API starts
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: marketplace-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - marketplace-net

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: marketplace-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - marketplace-net

  backend-api:
    build: .
    container_name: marketplace-api
    ports:
      - "8080:8080"
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/marketplace_db
      - SPRING_DATASOURCE_USERNAME=esra
      - SPRING_DATASOURCE_PASSWORD=esra1234
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      # --- REDIS CONNECTION FOR API ---
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - JWT_SECRET=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    depends_on:
      postgres-db:
        condition: service_started
      kafka:
        condition: service_started
      redis: # API now depends on Redis
        condition: service_healthy
    networks:
      - marketplace-net

# Infrastructure Definitions
networks:
  marketplace-net:
    driver: bridge

volumes:
  postgres_data: