version: '3.8'

services:
  # --- INFRASTRUCTURE LAYER ---
  marketplace-postgres:
    image: postgres:16-alpine
    container_name: marketplace-postgres
    environment:
      - POSTGRES_DB=marketplace_db
      - POSTGRES_USER=esra
      - POSTGRES_PASSWORD=esra1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - marketplace-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U esra -d marketplace_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  marketplace-redis:
    image: redis:7-alpine
    container_name: marketplace-redis
    ports:
      - "6379:6379"
    networks:
      - marketplace-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  marketplace-zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: marketplace-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - marketplace-net

  marketplace-kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: marketplace-kafka
    depends_on:
      - marketplace-zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: marketplace-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://marketplace-kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - marketplace-net

  # --- MICROSERVICES LAYER ---
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://marketplace-postgres:5432/marketplace_db
    depends_on:
      marketplace-postgres:
        condition: service_healthy
    networks:
      - marketplace-net

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://marketplace-postgres:5432/marketplace_db
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=marketplace-kafka:29092
      - SPRING_DATA_REDIS_HOST=marketplace-redis
    depends_on:
      marketplace-postgres:
        condition: service_healthy
      marketplace-kafka:
        condition: service_started
      marketplace-redis:
        condition: service_healthy
    networks:
      - marketplace-net

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://marketplace-postgres:5432/marketplace_db
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=marketplace-kafka:29092
    depends_on:
      marketplace-postgres:
        condition: service_healthy
      marketplace-kafka:
        condition: service_started
    networks:
      - marketplace-net

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8084:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=marketplace-kafka:29092
    depends_on:
      marketplace-kafka:
        condition: service_started
    networks:
      - marketplace-net

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - auth-service
      - product-service
      - inventory-service
    networks:
      - marketplace-net

# --- NETWORK & VOLUMES ---
networks:
  marketplace-net:
    driver: bridge

volumes:
  postgres_data: