apiVersion: v1
kind: Service
metadata:
  name: auth-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 8080 # Postman'den ulaşacağın port
      targetPort: 8080 # Konteynırın içindeki port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
      annotations: # <--- BURAYA DA EKLEYELİM
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: auth-service
          image: esrakonya/auth-service:v1
          imagePullPolicy: Never # Lokal build ettiğimiz imajı kullanması için
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://marketplace-postgres:5432/marketplace_db"
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "health,info,prometheus"
            - name: MANAGEMENT_METRICS_TAGS_APPLICATION
              value: "auth-service"
            - name: SPRING_DATASOURCE_USERNAME
              value: "esra"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "esra1234"
            - name: LOGSTASH_HOST
              value: "marketplace-logstash"
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT # Zipkin hatasını kesmek için
              value: "http://marketplace-zipkin:9411/api/v2/spans"
          # Eğer JWT Secret key'in application.yml içinde Environment Variable ise buraya ekle:
          # - name: JWT_SECRET_KEY
          #   value: "senin_cok_gizli_anahtarin"
          ports:
            - containerPort: 8080