apiVersion: v1
kind: Service
metadata:
  name: product-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 8080 # Dışarıdan 8082 ile erişeceğiz
      targetPort: 8080 # Konteynırın içindeki port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
      annotations: # <--- BURAYA DA EKLEYELİM
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: product-service
          image: esrakonya/product-service:v1
          imagePullPolicy: Never # ÖNEMLİ: Lokal imajı kullanması için (Docker Hub'a pushlamadıysan)
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://marketplace-postgres:5432/marketplace_db"
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "health,info,prometheus"
            - name: MANAGEMENT_METRICS_TAGS_APPLICATION
              value: "product-service"
            - name: SPRING_DATA_REDIS_HOST
              value: "marketplace-redis" # Henüz Redis'i kurmadık ama sorun olmaz
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "marketplace-kafka:29092"
            - name: LOGSTASH_HOST
              value: "marketplace-logstash" # localhost yerine K8s servis adını yazdık!
          ports:
            - containerPort: 8080