app:
  environment: prod

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8080
          predicates:
            - Path=/api/v1/auth/**

        - id: product-items
          uri: http://product-service:8080
          predicates:
            - Path=/api/v1/products/**
          filters:
            - name: CircuitBreaker
              args:
                name: productServiceCB
                fallbackUri: forward:/fallback/products

        - id: product-categories
          uri: http://product-service:8080
          predicates:
            - Path=/api/v1/categories/**

        - id: inventory-service
          uri: http://inventory-service:8080
          predicates:
            - Path=/api/v1/inventory/**

management:
  zipkin:
    tracing:
      # Directs the trace data to the Zipkin container in the Docker network
      endpoint: http://marketplace-zipkin:9411/api/v2/spans

# Inside application-prod.yml
LOGSTASH_HOST: marketplace-logstash