app:
  environment: local

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**

        - id: product-items
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/products/**
          filters:
            - name: CircuitBreaker
              args:
                name: productServiceCB
                fallbackUri: forward:/fallback/products

        - id: product-categories
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/categories/**

        - id: inventory-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/inventory/**