# --- GLOBAL SETTINGS ---
global:
  imagePullPolicy: IfNotPresent
  namespace: default
  imageTag: ""

# --- MICROSERVICES CONFIG ---
services:
  auth:
    name: auth-service
    image: esrakonya/auth-service
    port: 8080
  product:
    name: product-service
    image: esrakonya/product-service
    port: 8080
  gateway:
    name: gateway-service
    image: esrakonya/gateway-service
    port: 8080
    env:
      AUTH_SERVICE_URL: "http://auth-service:8080"
      PRODUCT_SERVICE_URL: "http://product-service:8080"
      INVENTORY_SERVICE_URL: "http://inventory-service:8080"
      LOGSTASH_HOST: "marketplace-logstash"
      SPRINGDOC_API_DOCS_ENABLED: "true"
  inventory:
    name: inventory-service
    image: esrakonya/inventory-service
    port: 8080
  notification:
    name: notification-service
    image: esrakonya/notification-service
    port: 8080
    env:
      LOGSTASH_HOST: "marketplace-logstash"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: "marketplace-kafka:29092"

# --- INFRASTRUCTURE CONFIG ---
infrastructure:
  postgres:
    name: marketplace-postgres
    image: postgres:16-alpine
    dbName: marketplace_db
    user: esra
    password: esra1234
    pvcName: postgres-pvc
  redis:
    name: marketplace-redis
    image: redis:7-alpine
  kafka:
    name: marketplace-kafka
    image: confluentinc/cp-kafka:7.4.0
    zookeeper: marketplace-zookeeper

# --- OBSERVABILITY CONFIG ---
observability:
  zipkin:
    name: marketplace-zipkin
    image: openzipkin/zipkin:3
  elasticsearch:
    name: marketplace-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1