app:
  environment: local
  message: Product Service on Local Machine

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/marketplace_db
    username: esra
    password: esra1234
  jpa:
    show-sql: true

  data:
    redis:
      host: localhost

  kafka:
    bootstrap-servers: localhost:9092