app:
  environment: prod
  message: Product Service on Docker

spring:
  datasource:
    url: jdbc:postgresql://marketplace-postgres:5432/marketplace_db
    username: esra
    password: esra1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  data:
    redis:
      host: marketplace-redis

  kafka:
    bootstrap-servers: marketplace-kafka:29092

management:
  zipkin:
    tracing:
      # Use the container name defined in docker-compose.yml
      endpoint: http://marketplace-zipkin:9411/api/v2/spans

# Inside application-prod.yml
LOGSTASH_HOST: marketplace-logstash